/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author deuzo
 */
public class ThisJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThisJFrame
     */
    public ThisJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUTON = new javax.swing.JButton();
        INNNN = new javax.swing.JTextField();
        ReSuLt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        l100rb = new javax.swing.JLabel();
        l50rb = new javax.swing.JLabel();
        l20rb = new javax.swing.JLabel();
        l10rb = new javax.swing.JLabel();
        l5rb = new javax.swing.JLabel();
        l2rb = new javax.swing.JLabel();
        l1rb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BUTON.setText("HITUNG!!!");
        BUTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTONActionPerformed(evt);
            }
        });

        INNNN.setToolTipText("DUIT");
        INNNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INNNNActionPerformed(evt);
            }
        });

        ReSuLt.setText("HASIL:");

        jLabel1.setText("DUIT:");

        l100rb.setText("100RB: ");

        l50rb.setText("50RB: ");

        l20rb.setText("20RB: ");

        l10rb.setText("10RB: ");

        l5rb.setText("5RB: ");

        l2rb.setText("2RB: ");

        l1rb.setText("1RB: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BUTON))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l100rb)
                    .addComponent(jLabel1)
                    .addComponent(ReSuLt)
                    .addComponent(INNNN, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l50rb)
                    .addComponent(l20rb)
                    .addComponent(l10rb)
                    .addComponent(l5rb)
                    .addComponent(l2rb)
                    .addComponent(l1rb))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INNNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReSuLt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l100rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l50rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l20rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l10rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l5rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l2rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUTON))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INNNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INNNNActionPerformed
        BUTONActionPerformed(evt);
    }//GEN-LAST:event_INNNNActionPerformed
    
    private void BUTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTONActionPerformed
        int duit;
        
        try {
            duit = Integer.parseInt(INNNN.getText());
        } catch (NumberFormatException e) {
            ReSuLt.setText("DeezNutz");
            return;
        }
        
        l100rb.setText("100RB: " + (duit / 100000) + " lembar");
        duit %= 100000;
        l50rb.setText("50RB: " + (duit / 50000) + " lembar");
        duit %= 50000;
        l20rb.setText("20RB: " + (duit / 20000) + " lembar");
        duit %= 20000;
        l10rb.setText("10RB: " + (duit / 10000) + " lembar");
        duit %= 10000;
        l5rb.setText("5RB: " + (duit / 5000) + " lembar");
        duit %= 5000;
        l2rb.setText("2RB: " + (duit / 2000) + " lembar");
        duit %= 2000;
        l1rb.setText("1RB: " + (duit / 1000) + " lembar");
    }//GEN-LAST:event_BUTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThisJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThisJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThisJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThisJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThisJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTON;
    private javax.swing.JTextField INNNN;
    private javax.swing.JLabel ReSuLt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l100rb;
    private javax.swing.JLabel l10rb;
    private javax.swing.JLabel l1rb;
    private javax.swing.JLabel l20rb;
    private javax.swing.JLabel l2rb;
    private javax.swing.JLabel l50rb;
    private javax.swing.JLabel l5rb;
    // End of variables declaration//GEN-END:variables
}
